### ISSUE TITLE
Allow for multiple configuration

### ISSUE THREAD

**Issue by analytically** [herdstat/herdstat-action#18]
It would be fantastic if we could add multiple 'repositories' configurations to group the repo's, each with a different SVG graph output, so we could see contributions per team.

**Comment by strieflinger** [comment]
I think that can be be supported by making the `herdstat` GitHub action accept the path to the configuration file. That would allow you to invoke the action multiple times in workflow (with different repositories to be analyzed and output path for the contribution graph SVG).

**Comment by strieflinger** [comment]
`herdstat` GitHub action now has a parameter to specify the configuration file. This can be used to implement the requested feature. See also #17 and the newly added note in the [README](https://github.com/herdstat/herdstat-action/blob/main/README.md).
